// Code generated by go run scripts/gen_enum_methods.go; DO NOT EDIT.
package domain

func (AttemptStatus) Values() []string {
	return []string{
		"in_progress",
		"paused",
		"completed",
	}
}

func AttemptStatusValues() []AttemptStatus {
	return []AttemptStatus{
		"in_progress",
		"paused",
		"completed",
	}
}
