// Code generated by go run scripts/gen_enum_methods.go; DO NOT EDIT.
package domain

func (SubscriptionStatus) Values() []string {
	return []string{
		"active",
		"expired",
		"canceled",
	}
}

func SubscriptionStatusValues() []SubscriptionStatus {
	return []SubscriptionStatus{
		"active",
		"expired",
		"canceled",
	}
}
