// Code generated by go run scripts/gen_enum_methods.go; DO NOT EDIT.
package domain

func (UserRole) Values() []string {
	return []string{
		"free",
		"pro",
		"admin",
	}
}

func UserRoleValues() []UserRole {
	return []UserRole{
		"free",
		"pro",
		"admin",
	}
}
