// Auto-generated TypeScript types from backend domain models
// DO NOT EDIT THIS FILE MANUALLY
// Regenerate with: pnpm gen:types

export interface User {
  id: string;
  email: string;
  role: 'free' | 'pro' | 'admin';
  subscriptionStatus: 'active' | 'expired' | 'canceled';
  createdAt: string;
}

export interface AnswerOption {
  id: string;
  answer: string;
  explanation: string;
}

export interface Question {
  id: string;
  examId: string;
  examSetId: string;
  examCode: string;
  question: string;
  questionType: 'multiple-choice' | 'multiple-select';
  answerOptions: AnswerOption[];
  correctAnswers: string[];
  overallExplanation: string;
  domain: string;
  imageUrl?: string;
  referenceUrls?: string[];
  createdAt: string;
}

export interface Attempt {
  id: string;
  userId: string;
  examId: string;
  examSetId: string;
  status: 'in_progress' | 'completed';
  score: number;
  totalQuestions: number;
  currentIndex: number;
  answers: Record<string, string[]>;
  startedAt: string;
  updatedAt: string;
  completedAt?: string | null;
}

export interface DomainScore {
  domainName: string;
  correctCount: number;
  totalCount: number;
  accuracyRate: number;
}

export interface UserExamStats {
  examId: string;
  userId: string;
  totalAttempts: number;
  totalScore: number;
  totalQuestionsAnswered: number;
  domainStats: Record<string, DomainScore>;
  lastTakenAt: string;
}
