// Code generated by tygo. DO NOT EDIT.

//////////
// source: attempt.go

/**
 * Attempt はユーザーの1回の受験データを表します。
 */
export interface Attempt {
  id: string;
  userId: string;
  examId: string; // 資格ID
  examSetId: string; // 模擬試験セットID
  status: AttemptStatus;
  score: number /* int */;
  totalQuestions: number /* int */;
  currentIndex: number /* int */;
  answers: { [key: string]: string[]}; // Key: QuestionID, Value: Selected Option IDs
  startedAt: string;
  updatedAt: string;
  CompletedAt?: string;
}
/**
 * AttemptStatus は受験の進捗状態を定義します。
 * tygo:enum
 */
export type AttemptStatus = "in_progress" | "paused" | "completed";
export const StatusInProgress: AttemptStatus = "in_progress"; // 進行中
export const StatusPaused: AttemptStatus = "paused"; // 中断中
export const StatusCompleted: AttemptStatus = "completed"; // 完了

//////////
// source: exam.go

/**
 * Exam は認定試験を表します（例: "Google Cloud Certified - Professional Cloud Developer"）。
 */
export interface Exam {
  id: string; // 例: "professional_cloud_developer"
  code: string; // 例: "PCD"
  name: string; // 例: "Professional Cloud Developer"
  description: string; // 例: "あなたの能力を評価します..."
  imageUrl: string; // 試験のロゴ/アイコンのURL
  createdAt: string;
}

//////////
// source: question.go

/**
 * Question は1つの問題を表すマスターデータです。
 */
export interface Question {
  id: string; // Document ID (e.g., "PCD_SET1_001")
  examId: string; // 資格ID (e.g., "professional_cloud_developer")
  examSetId: string; // 模擬試験セットID (e.g., "practice_exam_1")
  examCode: string; // 資格コード (e.g., "PCD")
  question: string; // HTML string
  questionType: string; // "multiple-choice" or "multi-select"
  answerOptions: AnswerOption[]; // 選択肢リスト
  correctAnswers: string[]; // 正解のOption IDリスト
  overallExplanation: string; // 全体の解説 (HTML)
  domain: string; // 分野 (e.g. "Compute")
  imageUrl?: string; // 解説図などのURL
  referenceUrls?: string[]; // 参考リンク
  createdAt: string;
}
/**
 * AnswerOption は問題の個々の選択肢です。
 */
export interface AnswerOption {
  id: string; // "a", "b", "c", "d" or UUID
  answer: string; // 選択肢の文言
  explanation: string; // この選択肢ごとの解説
}

//////////
// source: stats.go

/**
 * UserExamStats は「資格ごと(ExamID)」の累積成績です。
 */
export interface UserExamStats {
  UserID: string;
  ExamID: string;
  TotalAttempts: number /* int */;
  TotalScore: number /* int */; // 全てのAttemptでの合計正解数
  TotalQuestionsAnswered: number /* int */; // 全てのAttemptでの合計問題数
  DomainStats: { [key: string]: DomainScore};
  LastTakenAt: string;
}
/**
 * DomainScore は特定分野ごとの成績集計です。
 */
export interface DomainScore {
  domainName: string;
  correctCount: number /* int */;
  totalCount: number /* int */;
  accuracyRate: number /* int */; // パーセンテージ (0-100)
}

//////////
// source: user.go

/**
 * User はFirebase AuthのUIDをベースとした、アプリケーション独自のユーザー情報を保持します。
 * ロールとサブスクリプションの状態を管理し、アクセス制御に使用されます。
 */
export interface User {
  id: string; // Firebase Auth UID
  email: string;
  role: UserRole; // free, pro, admin
  subscriptionStatus: SubscriptionStatus; // active, expired, canceled
  createdAt: string;
}
/**
 * UserRole はユーザーの権限レベルを定義します。
 */
export type UserRole = "free" | "pro" | "admin";
/**
 * tygo:enum
 */
export const RoleFree: UserRole = "free"; // 無料ユーザー
/**
 * tygo:enum
 */
export const RolePro: UserRole = "pro"; // 有料サブスクリプションユーザー
/**
 * tygo:enum
 */
export const RoleAdmin: UserRole = "admin"; // 管理者
/**
 * SubscriptionStatus はサブスクリプションの状態を定義します。
 * tygo:enum
 */
export type SubscriptionStatus = "active" | "expired" | "canceled";
export const SubActive: SubscriptionStatus = "active";
export const SubExpired: SubscriptionStatus = "expired";
export const SubCanceled: SubscriptionStatus = "canceled";
