// Auto-generated TypeScript types from backend domain models
// DO NOT EDIT THIS FILE MANUALLY
// Regenerate with: npm run gen:types

export interface User {
  ID: string;
  Email: string;
  Role: 'free' | 'pro';
  SubscriptionStatus: 'active' | 'inactive' | 'trial';
  CreatedAt: string;
}

export interface AnswerOption {
  ID: string;
  Text: string;
  Explanation: string;
}

export interface Question {
  ID: string;
  ExamID: string;
  ExamSetID: string;
  ExamCode: string;
  QuestionText: string;
  QuestionType: 'multiple-choice' | 'multiple-select';
  Options: AnswerOption[];
  CorrectAnswers: string[];
  OverallExplanation: string;
  Domain: string;
  CreatedAt: string;
}

export interface Attempt {
  ID: string;
  UserID: string;
  ExamID: string;
  ExamSetID: string;
  Status: 'in_progress' | 'completed';
  Score: number;
  TotalQuestions: number;
  CurrentIndex: number;
  Answers: Record<string, string[]>;
  StartedAt: string;
  UpdatedAt: string;
  CompletedAt?: string | null;
}

export interface DomainScore {
  DomainName: string;
  CorrectCount: number;
  TotalCount: number;
  AccuracyRate: number;
}

export interface UserExamStats {
  ExamID: string;
  UserID: string;
  TotalAttempts: number;
  TotalScore: number;
  TotalQuestionsAnswered: number;
  DomainStats: Record<string, DomainScore>;
  LastTakenAt: string;
}
